declare const styles: {
  readonly reasonBar: string;
  readonly reasonSeg: string;
  readonly rMissing: string;
  readonly rTimeout: string;
  readonly rAuth: string;
  readonly rNetwork: string;
  readonly rCorrupt: string;
  readonly rOther: string;
  readonly barFill: string;
  readonly barFillBad: string;
  readonly trendPlot: string;
  readonly trendArea: string;
  readonly trendSvg: string;
  readonly trendGrid: string;
  readonly trendFill: string;
  readonly trendLine: string;
  readonly trendCrosshair: string;
  readonly trendDot: string;
};
export = styles;
