declare const styles: {
  readonly container: string;
  readonly header: string;
  readonly titleWrap: string;
  readonly livePulse: string;
  readonly title: string;
  readonly count: string;
  readonly grid: string;
  readonly card: string;
  readonly fileName: string;
  readonly sessionId: string;
  readonly progressWrap: string;
  readonly progressFill: string;
  readonly progressIndeterminate: string;
  readonly stats: string;
  readonly bytes: string;
  readonly bytesTotal: string;
  readonly rate: string;
  readonly providerStrip: string;
  readonly providerChip: string;
  readonly providerChipPrimary: string;
  readonly providerChipHost: string;
  readonly providerChipCount: string;
};
export = styles;
